[UI]: working on the feeds screen
droidconKE/droidconKE2022ReactNative pull request #57
Opened 2022-10-18 13:14 UTC by Mogakamo

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #11 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-10-18 13:15 UTC, Mogakamo commented
Still finalizing on the styling

2022-10-19 04:39 UTC, makunomark commented
Hey @Mogakamo 
please expect the response from the api to look like this:
```json
{
    "data": [
        {
            "title": "Test",
            "body": "Good one",
            "topic": "droidconweb",
            "url": "https://droidcon.co.ke",
            "image": "http://localhost:8000/upload/event/feeds/dangyntvmaet8jgjpg.jpg",
            "created_at": "2020-03-19 18:45:49"
        },
        {
            "title": "niko fine",
            "body": "this is a test",
            "topic": "droidconweb",
            "url": "https://droidcon.co.ke",
            "image": null,
            "created_at": "2020-03-19 18:43:38"
        }
    ],
    "meta": {
        "paginator": {
            "count": 2,
            "per_page": "10",
            "current_page": 1,
            "next_page": null,
            "has_more_pages": false,
            "next_page_url": null,
            "previous_page_url": null
        }
    }
}
```

2022-10-20 08:25 UTC, brianwachira requested changes

2022-10-20 08:25 UTC, brianwachira commented on src/screens/FeedScreen.tsx
> +];
Uhm, the expect the response from the api will look something like this:
```json
{
    "data": [
        {
            "title": "Test",
            "body": "Good one",
            "topic": "droidconweb",
            "url": "https://droidcon.co.ke",
            "image": "http://localhost:8000/upload/event/feeds/dangyntvmaet8jgjpg.jpg",
            "created_at": "2020-03-19 18:45:49"
        },
        {
            "title": "niko fine",
            "body": "this is a test",
            "topic": "droidconweb",
            "url": "https://droidcon.co.ke",
            "image": null,
            "created_at": "2020-03-19 18:43:38"
        }
    ],
    "meta": {
        "paginator": {
            "count": 2,
            "per_page": "10",
            "current_page": 1,
            "next_page": null,
            "has_more_pages": false,
            "next_page_url": null,
            "previous_page_url": null
        }
    }
}
```

So you can use this JSON instead

2022-10-21 05:56 UTC, Mogakamo commented on src/screens/FeedScreen.tsx
> +];
Ok let me work on it.

2022-11-03 11:27 UTC, brianwachira requested changes

2022-11-03 11:27 UTC, brianwachira commented on src/components/cards/FeedsCard.tsx
> +          {/* <FeedIcon style={styles.feed_icon} /> */}
Add the correct share icon based on the [design](https://xd.adobe.com/view/dd5d0245-b92b-4678-9d4a-48b3a6f48191-880e/screen/aabbe326-f4d9-4fae-9cbc-433491567613/specs/).
- Download the icon in SVG format from the design
- Convert the SVG icon into a component using the link https://react-svgr.com/playground/?native=true&typescript=true
- Save it in the assets/icons folder. You can also check out how the other icon components have been done.

2022-11-03 11:27 UTC, brianwachira commented on src/components/cards/FeedsCard.tsx
> +    width: 318,
The image is not spanning the full width of the screen
![photo_2022-11-03_14-13-28](https://user-images.githubusercontent.com/28436092/199706879-a0a519a9-4fdd-4ba4-994d-8f15cfc25fa8.jpg)

- You can set image width as a flexible property.
Change the width from `318` to  `100%` instead.

2022-11-03 11:27 UTC, brianwachira commented on src/components/cards/FeedsCard.tsx
> +    fontFamily: fonts.MONTSERRAT_BOLD,
As per the [design](https://xd.adobe.com/view/dd5d0245-b92b-4678-9d4a-48b3a6f48191-880e/screen/aabbe326-f4d9-4fae-9cbc-433491567613/specs/)
fontSize and fontFamily should be 
`
    fontSize: 12,
    fontFamily: fonts.MONTSERRAT_REGULAR,
`

Please change accordingly

2022-11-03 11:27 UTC, brianwachira commented on src/screens/FeedScreen.tsx
> +      </ScrollView>
So the flatlist is vertically scrollable by default. You can check out [React Native Docs](https://reactnative.dev/docs/flatlist) for more information.
In that case, do away with the scrollview the define `styles.paddingHorizontal` on the flatlist.

2022-11-03 11:27 UTC, brianwachira commented on src/screens/FeedScreen.tsx
> +console.log(FEED[0].data);
You can clean out this console log.

2022-11-07 06:54 UTC, brianwachira requested changes

2022-11-07 06:54 UTC, brianwachira commented on src/components/cards/FeedsCard.tsx
> +    width: 100%,
![image](https://user-images.githubusercontent.com/28436092/200243939-cde8e547-3827-4abe-b13c-fcefae7c87d7.png)
- wrap `100%` on single quotes

2022-11-07 19:23 UTC, brianwachira approved these changes

2022-11-07 19:23 UTC, merged